/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: {
      burgundy: '#800020',
      'bright-red': '#FF0000',
      'dark-gray': '#A9A9A9',
      'deep-ocean-blue': '#000080',
      'dark-orange': '#FF8C00',
      'deep-sky-blue': '#00BFFF',
      'dodger-blue': '#1E90FF',
      'forest-green': '#228B22',
      gold: '#FFD700',
      'light-gray': '#D3D3D3',
      'lime-green': '#32CD32',
      'medium-sea-green': '#3CB371',
      'mustard-yellow': '#FFDB58',
      'off-white': '#F5F5F5',
      orange: '#FFA500',
      'sandy-beige': '#D2B48C',
      'steel-blue': '#759FCB',
      'sky-blue': '#87CEEB',
      'sunshine-yellow': '#FFD700',
      yellow: '#FFFF00',
      'system-blue': '#8FB9FF',
      'system-blue-light': '#C2D9FF',
      'system-blue-700': '#50B4E2',
      'system-brown': '#3A332C',
      'system-brown-light': '#8C7B69',
      'system-brown-medium': '#BD8850',
      'system-gray': '#697A8C',
      'system-gray-dark': '#2C333A',
      'system-gray-light': '#AEB8C2',
      'system-lace': '#FFF7EB',
      'system-manila': '#e7c9a9',
      'system-manila-dark': '#cba175',
      'system-navy': '#183656',
      'system-off': '#E93835',
      'system-off-muted': '#F1807E',
      'system-orange': '#FFA85C',
      'system-papaya': '#FFF7EB',
      'system-platinum': '#D9D9D9',
      'system-platinum-dark': '#C0C0C0',
      'system-toggled': '#24E56B',
      'system-toggled-light': '#7FF0A9',
      'system-toggled-muted': '#698C8C',
      'system-wheat': '#FFE7C2',
    },
    extend: {},
  },
  plugins: [],
}

